name: 'Change new UAT PR to draft'
on:
    pull_request:
        types:
            - opened
        branches:
            - 'uat'
jobs:
    create_uat_pr:
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.pull_request.head.ref, 'gs-pipeline') }}
        env:
            GH_TOKEN: ${{ secrets.GTHB_TOKEN }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
        steps:
            - uses: actions/checkout@v4
            - id: uat_pr_draft
              run: |
                gh pr ready $PR_NUMBER --undo