name: 'Create UAT PR to draft on INT PR creation'
on:
    pull_request:
        types:
            - opened
        branches:
            - 'int'
jobs:
    create_uat_pr:
        runs-on: ubuntu-latest
        if: contains(${{ github.event.pull_request.base.ref }}, 'gs-pipeline')
        env:
            GH_TOKEN: ${{ secrets.GTHB_TOKEN }}
            PR_TITLE: ${{ github.event.pull_request.title }}
            PR_BODY: ${{ github.event.pull_request.body }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Work out base branch name
              id: base_branch
              run: |
                echo ${{ github.event.pull_request.base.ref }}
                .github/workflows/scripts/substring.sh
                echo ${{ steps.base_branch.outputs.base_name }}

            - name: Create UAT PR
              id: uat_pr
              run: |
                git checkout uat
                gh pr create -t$PR_TITLE -b$PR_BODY -Buat -H${{ steps.base_branch.outputs.base_name }} -d