name: 'Create UAT PR to draft on INT PR creation'
on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
        branches:
            - 'int'
jobs:
    change_new_pr_to_draft:
        runs-on: ubuntu-latest
        if: contains(${{ github.event.pull_request.base.ref }}, 'gs-pipeline')
        env:
            GH_TOKEN: ${{ secrets.GTHB_TOKEN }}
            PR_DETAILS: ${{ github.event.number }}
        steps:
            - uses: actions/checkout@v4
            - run: .github/workflows/scripts/substring.sh >> $GITHUB_OUTPUT
            - run: gh pr create --title $PR_DETAILS.pull_request.title --base uat --head <original feature branch> --draft
