name: 'Create UAT PR to draft on INT PR creation'
on:
    pull_request:
        types:
            - opened
        branches:
            - 'int'
jobs:
    create_uat_pr:
        runs-on: ubuntu-latest
        if: contains(${{ github.event.pull_request.head.ref }}, 'gs-pipeline')
        env:
            GH_TOKEN: ${{ secrets.GTHB_TOKEN }}
            PR_TITLE: ${{ github.event.pull_request.title }}
            PR_BODY: ${{ github.event.pull_request.body }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - id: base-branch              
              run: |
                echo ${{ github.event.pull_request.head.ref }}
                .github/workflows/scripts/substring.sh                
              shell: bash
            - id: uat_pr              
              run: |
                echo ${{ steps.base-branch.outputs.base_name }}
                gh pr create -t$PR_TITLE -b$PR_BODY -Buat -H${{ steps.base-branch.outputs.base_name }} -d