name: 'Update and merge UAT PR'
on:
    workflow_dispatch:
        inputs:
            issueId:
                type: string
jobs:
    update_merge_uat:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GTHB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - id: uat_pr_merge
              run: |
                echo "${{ inputs.issueId }}"
                PR_NUMBER=$(gh pr list --search "base:uat ${{ inputs.issueId}} in:title type:pr is:open" --json "number" --jq ".[0].number")
                gh pr ready $PR_NUMBER
                gh pr merge $PR_NUMBER